### ISSUE TITLE
Error while registering packets

### ISSUE THREAD

**Issue by casparml** [NEZNAMY/VelocityScoreboardAPI#4]
[VelocityScoreboardAPI]: An error occurred while registering packets. This most likely means Velocity had a breaking change and this plugin needs an update.

full log:
[latest.log](https://github.com/user-attachments/files/17691248/latest.log)

**Comment by NEZNAMY** [comment]
`Can not register class TeamPacket with id 62 for 1.8 because another packet is already registered`
That packet was already previously registered by `velocitab`. That's not an issue in this plugin.

**Comment by WiIIiam278** [comment]
Velocitab is not compatible with VelocityScoreboardAPI. Since both plugins use similar registration logic, this conflict occurs. You don't need this plugin with Velocitab. Uninstall VelocityScoreboardAPI in this case.
