### ISSUE TITLE
Player nametags not visible

### ISSUE THREAD

**Issue by bobcat4848** [NEZNAMY/VelocityScoreboardAPI#5]
Player nametags seem to not be showing even though their tags are specified in the groups.yml. Worked on Bungeecord/Waterfall.

scoreboard-teams is enabled in my tab config.yml as well

Velocity 3.4.0-SNAPSHOT and Paper version 1.21.1-131-ver/1.21.1@84281ce
Running Tab v5.0.1 and VelocityScoreBoardAPI version 1.0.5 and TabBridge version v6.0.0

groups.yml:
_DEFAULT_:
  tabprefix: "%luckperms_prefix%"
  customtabname: "%essentials_nickname%"
  tabsuffix: "%luckperms_suffix%"
  tagprefix: "%luckperms_prefix%"
  customtagname: "%essentials_nickname%"
  tagsuffix: "%luckperms_suffix%"

**Comment by NEZNAMY** [comment]
You are most likely reporting it in the wrong repository. I recommend you to check TAB's repository for a discord link where you can get help.
